IP_ADDRESS: "127.0.0.1"
PORT: "8000"

SPOTIFY_ACCESS_TOKEN: "Bearer BQAeseig3txOGb_IKbiIuMICmUp3OhxNW3-kKUNjaBkIZgWPspcWHHWWtFTZtSGzDIswiTpMSxkAly6msIZv_RlULsGfBWfGYSzimmd5jli69GAwSdvG2Y5cjJhTWW96-fqtdokqqkq7PlpP"
SPOTIFY_REFRESH_TOKEN: "AQDY0NhDoYBp2yXZIIleFrHdup_vrFMgfjMrPz4pejKR7TWOisGz6m8j5WFNATZ_b0dVDB5SQJk697bm5WAyZXCrep0htd6goa254YzmkQDApcxNNk6idOU7cTONwduZ_vo"
SPOTIFY_API_DOMAIN: "https://api.spotify.com/v1/"
LIMIT_ARTIST: "30"
