IP_ADDRESS: "127.0.0.1"
PORT: "8000"

SPOTIFY_API_ENDPOINT: "https://api.spotify.com/v1/"
SPOTIFY_REFRESH_ENDPOINT: "https://accounts.spotify.com/api/token"
SPOTIFY_REFRESH_TOKEN: "AQDY0NhDoYBp2yXZIIleFrHdup_vrFMgfjMrPz4pejKR7TWOisGz6m8j5WFNATZ_b0dVDB5SQJk697bm5WAyZXCrep0htd6goa254YzmkQDApcxNNk6idOU7cTONwduZ_vo"
SPOTIFY_AUTHORIZATION_TOKEN: "Basic ZWZiY2RkZDMxNjM4NDcxMjhhNzRkYmE5M2QwMzk1ZjY6NGQ3Mzk5Nzg4NDU3NGQ5NDhjMDU4ZDAwMjRkYWJhMDc="
LIMIT_ARTIST: "30"

READ_TIMEOUT: 15
WRITE_TIMEOUT: 15

CSV_PATH: "./test/bateria_csv/pokemon.csv"
CSV_ARTIST_PATH: "./test/bateria_csv/artist.csv"

